import = [
    "~/.config/alacritty/themes/themes/catppucin_frappe.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 13

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[window]
opacity = 0.9
blur = true
#decorations_theme_variant = "Dark"
