omnivore_api_key: ENC[AES256_GCM,data:NlG1H3vs4pYiEasy1pJayTHZHkMRWXpy9jcUwvOCrlm+XMIz,iv:mWc+KLDrOS6Wh64Z7Y7AwcdhlLmxU2rMxh9PE6fbqoE=,tag:Zc8kQqElLjoQ+L9uxZLj4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18eudkaryvhday2ggpkejwwr6ntr6mj7d2v76t4asq4gcxdlqda6q6hj844
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TFJBN0lOSUQ1dnRydzFR
            Mi9pejIvQjNnSlFadWQrMnlDWG84RjdiLzFVCkl5eUk2Y1dlN3o4NElSNC9IQ0d0
            UEVIeTlsVXJCcktlemtWdkMwWE1kclEKLS0tIENqWmU1UW9BSy9Fd1hJOFFnWFR5
            SVNRWEE3YmRncGtLMllWbENsNEhIWG8Kdoq+4endYDlkvzMFQyz5w86rue1S07rI
            vlnYG5FZKIVIAFVsFZZ96a7w8SUueNOK9rhs6V+NzNomDKvLvqZYnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T13:26:10Z"
    mac: ENC[AES256_GCM,data:kyb1ubEPrnKvKd7BcynPsqiSf1dLiEK+MRr9g9qY/CkwRbDRR+tU/ihHeiegrLqxRk1p4zZnYB/QuPakdnQRE/i3I11LgbQSnRoKct+uIVfhrBTYdZg0dNfiNIoxFrdUuuGglB44RyWUbkk/u78WntjVUF7wHKQuhD7wvlTZ1kw=,iv:jAIkdI1CrGBYmB8c2IrLioppsKmgwzNaYdVAdwG6EJQ=,tag:i0Va16oBtLdurBC1iuQfyA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
